server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest

      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    com.example.paymentapp: DEBUG

  file:
    name: /logs/payment-app/payment.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"