server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    root: INFO
    com.example.orderapp: DEBUG

  file:
    name: /logs/order-app/order.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"